// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0CD9TGS3KtvWG63DuDC1Xqh2WFki0n1w',
    appId: '1:850115765836:web:7e458ae0e76f9f8555f6e9',
    messagingSenderId: '850115765836',
    projectId: 'finale-c1cbb',
    authDomain: 'finale-c1cbb.firebaseapp.com',
    storageBucket: 'finale-c1cbb.appspot.com',
    measurementId: 'G-16QHVRE5VR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvTNVdYcQZgL47D26HXiW7XRb-2H1Ic84',
    appId: '1:850115765836:android:f9d2df161cf0142f55f6e9',
    messagingSenderId: '850115765836',
    projectId: 'finale-c1cbb',
    storageBucket: 'finale-c1cbb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB4dXk5ygJB1NT7pJi-75HAGgOAHa4pSg',
    appId: '1:850115765836:ios:658c86a8df3d676555f6e9',
    messagingSenderId: '850115765836',
    projectId: 'finale-c1cbb',
    storageBucket: 'finale-c1cbb.appspot.com',
    iosBundleId: 'com.example.finale',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB4dXk5ygJB1NT7pJi-75HAGgOAHa4pSg',
    appId: '1:850115765836:ios:658c86a8df3d676555f6e9',
    messagingSenderId: '850115765836',
    projectId: 'finale-c1cbb',
    storageBucket: 'finale-c1cbb.appspot.com',
    iosBundleId: 'com.example.finale',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0CD9TGS3KtvWG63DuDC1Xqh2WFki0n1w',
    appId: '1:850115765836:web:9bac21b9416b5afb55f6e9',
    messagingSenderId: '850115765836',
    projectId: 'finale-c1cbb',
    authDomain: 'finale-c1cbb.firebaseapp.com',
    storageBucket: 'finale-c1cbb.appspot.com',
    measurementId: 'G-YL6FYWJ1XX',
  );
}
